# Generated by Django 5.1.4 on 2024-12-20 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Auth', models.CharField(max_length=100)),
                ('Year', models.IntegerField()),
                ('Gender', models.CharField(max_length=100)),
            ],
        ),
    ]
