# Generated by Django 5.1.3 on 2024-11-21 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('singapp', '0003_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
