# Generated by Django 5.1.3 on 2024-11-14 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demartapp', '0002_customer_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_details',
            old_name='product_price',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='customer_details',
            old_name='product_quantity',
            new_name='product_phoneno',
        ),
    ]
