# Generated by Django 5.1.3 on 2024-11-14 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demartapp', '0003_rename_product_price_customer_details_product_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_details',
            old_name='product_id',
            new_name='customer_id',
        ),
        migrations.RenameField(
            model_name='customer_details',
            old_name='product_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product_details',
            old_name='product_name',
            new_name='name',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('quantity_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demartapp.customer_details')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demartapp.product_details')),
            ],
        ),
    ]
