# Generated by Django 5.1.3 on 2024-11-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demartapp', '0005_remove_customer_details_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_details',
            name='quantity_in_stock',
            field=models.IntegerField(default=0),
        ),
    ]
