# Generated by Django 5.1.3 on 2024-11-14 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demartapp', '0006_product_details_quantity_in_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_details',
            old_name='product_price',
            new_name='price',
        ),
    ]
